AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  matchmaker

  Sample SAM Template for matchmaker
  
Parameters:
  Env:
    Default: dev
    Type: String

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        ENVIRONMENT: !Ref Env

Resources:
  CreateDevelopersPairFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create-developers-pair.lambdaHandler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        -  src/handlers/create-developers-pair.ts

  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "rate(365 days)" # "cron(30 9 * * 1)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: !GetAtt "CreateDevelopersPairFunction.Arn"
          Id: "CreateDevelopersPairFunction"
  
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "CreateDevelopersPairFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt "ScheduledRule.Arn"

  DevelopersDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub developers-${Env}
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  LambdaDynamoDbWriteConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: CreateDevelopersPairFunction
      Destination:
        Id: DevelopersDynamoDBTable
      Permissions:
        - Write
        - Read

  SQSQueueNotifier:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Sub SQSQueuePairsNotifier-${Env}

Outputs:
  Databse:
    Description: "databse"
    Value: !GetAtt DevelopersDynamoDBTable.Arn
  QueueARN:
    Description: "SQS pairs queue notifier Arn"
    Value: !GetAtt SQSQueueNotifier.Arn
  QueueURL:
    Description: "SQS pairs queue notifier URL"
    Value: !GetAtt SQSQueueNotifier.QueueUrl