AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  matchmaker

  Sample SAM Template for matchmaker
  
Parameters:
  Env:
    Default: dev
    Type: String

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        ENVIRONMENT: !Ref Env
        SQS_QUEUE_URL: !GetAtt SQSQueueNotifier.QueueUrl

Resources:
  CreateDevelopersPairFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub create-developers-pair-${Env}
      Handler: create-developers-pair.lambdaHandler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        -  src/handlers/create-developers-pair.ts

  ManageMatchmakerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub manage-matchmaker-${Env}
      Handler: manage-matchmaker.lambdaHandler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        -  src/handlers/manage-matchmaker.ts
  
  SendPairNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub send-pair-notifier-${Env}
      Handler: send-pair-notifier.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSQueueNotifier.Arn
            BatchSize: 1
      Environment:
        Variables:
          DISCORD_WEBHOOK_ID: !Sub "{{resolve:ssm:/${Env}/discord/webhooks/id}}"
          DISCORD_WEBHOOK_TOKEN: !Sub "{{resolve:ssm:/${Env}/discord/webhooks/token}}"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        -  src/handlers/send-pair-notifier.ts

  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "rate(365 days)" # "cron(30 9 * * 1)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: !GetAtt "CreateDevelopersPairFunction.Arn"
          Id: "CreateDevelopersPairFunction"
  
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "CreateDevelopersPairFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt "ScheduledRule.Arn"

  DevelopersDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub developers-${Env}
      # BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  LambdaDynamoDbConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: CreateDevelopersPairFunction
      Destination:
        Id: DevelopersDynamoDBTable
      Permissions:
        - Write
        - Read

  SQSQueueNotifier:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Sub SQSQueuePairsNotifier-${Env}

Outputs:
  DatabaseName:
    Description: "databse"
    Value: !Ref DevelopersDynamoDBTable 
  QueueARN:
    Description: "SQS pairs queue notifier Arn"
    Value: !GetAtt SQSQueueNotifier.Arn
  QueueURL:
    Description: "SQS pairs queue notifier URL"
    Value: !GetAtt SQSQueueNotifier.QueueUrl
