import { BatchWriteItemCommand, BatchWriteItemCommandInput, DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';
import { randomUUID } from 'crypto';
import { logger } from '../common';

const dynamoClient = new DynamoDBClient({ region: 'us-east-1' });
const ddbDocClient = DynamoDBDocumentClient.from(dynamoClient);

const developers = [
    {
        Name: 'Juandi',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'juandiego@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '20/11/1982',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'UX/UI Lead',
        'Mes de cumple': 'November',
        'Nombre completo': 'Juan Diego Montero',
        Tribu: 'UX/UI',
    },
    {
        Name: 'Nico',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'nicolas@tinkin.one',
        'Favorite Dessert': '3 leches',
        'Fecha de nacimiento': '13/01/1989',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Founder',
        'Mes de cumple': 'January',
        'Nombre completo': 'Nicolas Schmitt',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Chan',
        City: 'Atuntaquí',
        Country: 'Ecuador',
        Email: 'chan@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '09/04/1985',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Founder',
        'Mes de cumple': 'April',
        'Nombre completo': 'Amstrong Huang',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Dennis',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'dennis@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '28/08/1983',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Founder',
        'Mes de cumple': 'August',
        'Nombre completo': 'Dennis Espinoza',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Paul',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'paul@tinkin.one',
        'Favorite Dessert': 'Postre de tres leches',
        'Fecha de nacimiento': '30/04/1988',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Gerente',
        'Mes de cumple': 'April',
        'Nombre completo': 'Paul Jarrin',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Dani',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'daniela@tinkin.one',
        'Favorite Dessert': 'Tiramisu 🍪',
        'Fecha de nacimiento': '21/05/1992',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'PO',
        'Mes de cumple': 'May',
        'Nombre completo': 'Daniela Soto',
        Tribu: 'Product owner',
    },
    {
        Name: 'Estefi',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'estefania@tinkin.one',
        'Favorite Dessert': 'Apple pie 🥧',
        'Fecha de nacimiento': '02/05/1985',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Coordinadora Administrativa',
        'Mes de cumple': 'May',
        'Nombre completo': 'Estefanía Bravo',
        Tribu: 'Administración',
    },
    {
        Name: 'Belu',
        City: 'Bariloche',
        Country: 'Argentina',
        Email: 'belen@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '26/06/1991',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'UX/UI Designer',
        'Mes de cumple': 'June',
        'Nombre completo': 'Belén Marte',
        Tribu: 'UX/UI',
    },
    {
        Name: 'Facu',
        City: 'Córdoba',
        Country: 'Argentina',
        Email: 'facundo@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '15/04/1995',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'UX/UI Designer',
        'Mes de cumple': 'April',
        'Nombre completo': 'Facundo Artal',
        Tribu: 'UX/UI',
    },
    {
        Name: 'Anitta',
        City: 'Córdova',
        Country: 'Argentina',
        Email: 'ana@tinkin.one',
        'Favorite Dessert': 'Panqueques con dulce de leche 🥞',
        'Fecha de nacimiento': '22/04/1990',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'UX/UI Designer',
        'Mes de cumple': 'April',
        'Nombre completo': 'Ana Laura Fayos',
        Tribu: 'UX/UI',
    },
    {
        Name: 'Romi',
        City: 'Buenos AIres',
        Country: 'Argentina',
        Email: 'romina@tinkin.one',
        'Favorite Dessert': 'Torta de chocolate con nutella',
        'Fecha de nacimiento': '27/03/1996',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'UX/UI Designer',
        'Mes de cumple': 'March',
        'Nombre completo': 'Romina Soifer',
        Tribu: 'UX/UI',
    },
    {
        Name: 'Vale',
        City: 'Buenos Aires',
        Country: 'Argentina',
        Email: 'valeria@tinkin.one',
        'Favorite Dessert': 'Volcán de chocolate 🍪',
        'Fecha de nacimiento': '01/04/1996',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'UX/UI Designer',
        'Mes de cumple': 'April',
        'Nombre completo': 'Valeria Agrofoglio',
        Tribu: 'UX/UI',
    },
    {
        Name: 'Mica',
        City: 'Buenos Aires',
        Country: 'Argentina',
        Email: 'micaela@tinkin.one',
        'Favorite Dessert': 'Volcán de chocolate con una bocha de helado 🌋🍦',
        'Fecha de nacimiento': '20/02/1997',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'UX/UI Designer',
        'Mes de cumple': 'February',
        'Nombre completo': 'Micaela Lavecchia',
        Tribu: 'UX/UI',
    },
    {
        Name: 'Alex',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'alex@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '03/08/1997',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'August',
        'Nombre completo': 'Alex Arevalo',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Andrés V',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'avelasco@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '16/08/1996',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'August',
        'Nombre completo': 'Andrés Velasco',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Ian',
        City: 'General Mosconí',
        Country: 'Argentina',
        Email: 'ian@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '30/10/2000',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'October',
        'Nombre completo': 'Ian Ferreyra',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Migue',
        City: 'El Carmen',
        Country: 'Ecuador',
        Email: 'miguel@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '14/09/1999',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'September',
        'Nombre completo': 'Miguel Jurado',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Pedro',
        City: 'Manta',
        Country: 'Ecuador',
        Email: 'pedro@tinkin.one',
        'Favorite Dessert': 'Helado de vainilla 🍦',
        'Fecha de nacimiento': '28/11/1997',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'November',
        'Nombre completo': 'Pedro Altamirano',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Tella',
        City: 'Buenos Aires',
        Country: 'Argentina',
        Email: 'mariano@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '07/10/1990',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'October',
        'Nombre completo': 'Mariano Tellaeche',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Washo',
        City: 'Ibarra',
        Country: 'Ecuador',
        Email: 'washington@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '02/08/1999',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'August',
        'Nombre completo': 'Washington Pijal Toapanta',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Ari',
        City: 'Ibarra',
        Country: 'Ecuador',
        Email: 'arianna@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '24/03/1999',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'March',
        'Nombre completo': 'Arianna Belen Armijos Inga',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Lucila',
        City: 'Trelew',
        Country: 'Argentina',
        Email: 'lucila@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '04/04/1997',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'April',
        'Nombre completo': 'Lucila Allende',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Gastón',
        City: 'Córdoba',
        Country: 'Argentina',
        Email: 'gaston@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '10/05/1995',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'May',
        'Nombre completo': 'Gastón Odetti Di Fiori',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Mabe',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'mceron@tinkin.one',
        'Favorite Dessert': 'Cheesecake de mora 🍰 y Tiramisú 🥮',
        'Fecha de nacimiento': '28/12/2000',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'December',
        'Nombre completo': 'María Belén Cerón',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Lenin',
        City: 'Ambato',
        Country: 'Ecuador',
        Email: 'lenin@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '02/04/2003',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'April',
        'Nombre completo': 'Lenin Mazabanda',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Alex C',
        City: '',
        Country: 'Ecuador',
        Email: 'achicaiza@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '',
        'Fecha salida': '27/12/2022',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': '',
        'Nombre completo': 'Alex Chicaiza',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Exe',
        City: 'Buenos Aires',
        Country: 'Argentina',
        Email: 'emassimelli@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '23/02/1996',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'February',
        'Nombre completo': 'Exequiel Massimelli',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Juanfra',
        City: 'Loja',
        Country: 'Ecuador',
        Email: 'jcevallos@tinkin.one',
        'Favorite Dessert': 'Cheesecake 🍪',
        'Fecha de nacimiento': '30/03/1999',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'March',
        'Nombre completo': 'Juan Francisco Cevallos',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Xavi',
        City: 'Cuenca',
        Country: 'Ecuador',
        Email: 'xmendez@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '22/05/1996',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': 'May',
        'Nombre completo': 'Xavier Méndez',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Esteban_Alvear',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'enalvear@outlook.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '30/11/2022',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': '',
        'Nombre completo': 'Esteban Nicolas Alvear Mancero',
        Tribu: '',
    },
    {
        Name: 'Renato_Salazar',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'renatosalazar29d@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '30/11/2022',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': '',
        'Nombre completo': 'Paul Renato Salazar Mendoza',
        Tribu: '',
    },
    {
        Name: 'Andrés_Zambrano',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'waza1995@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '17/10/2022',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': '',
        'Nombre completo': 'Washington Andrés Zambrano Andrade',
        Tribu: '',
    },
    {
        Name: 'Richard_Aguilar',
        City: 'Quinindé',
        Country: 'Ecuador',
        Email: 'richard.aguilar.2020@hotmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '11/11/2022',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': '',
        'Nombre completo': 'Richard Anthony Aguilar Montaño',
        Tribu: '',
    },
    {
        Name: 'Jorge_Pita',
        City: 'Guayaquil',
        Country: 'Ecuador',
        Email: 'jbpita@espol.edu.ec',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '05/08/2022',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': '',
        'Nombre completo': 'JORGE BRYAN PITA ESTRELLA',
        Tribu: '',
    },
    {
        Name: 'Germán_Binder',
        City: 'La Plata',
        Country: 'Ecuador',
        Email: 'bindergerman@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '10/01/2023',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': '',
        'Nombre completo': 'Germán Binder',
        Tribu: '',
    },
    {
        Name: 'Juanfer_Ortiz',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'juan_dk148@hotmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '10/01/2023',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': '',
        'Nombre completo': 'Juan Fernando Ortiz',
        Tribu: '',
    },
    {
        Name: 'Diana_Segura',
        City: 'Guayaquil',
        Country: 'Ecuador',
        Email: 'dianeli.segumi@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '20/05/2022',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Diana Segura',
        Tribu: '',
    },
    {
        Name: 'Edwin_Guamushig',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'edwin.paul.73@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '23/09/2022',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Edwin Paul Guamushig Gualotuña',
        Tribu: '',
    },
    {
        Name: 'Roberto_Cortés',
        City: 'CDMX',
        Country: 'México',
        Email: '',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '28/06/2021',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Roberto  Cortés Monroy',
        Tribu: '',
    },
    {
        Name: 'Danny_Guanuna',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'dannyajila2000@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '11/07/2022',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': '',
        'Nombre completo': 'Danny Alexander Guañuna Ajila',
        Tribu: '',
    },
    {
        Name: 'Jorge_Luis_Ortiz',
        City: 'Azogues',
        Country: 'Ecuador',
        Email: 'jorgeortizc05@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '28/03/2022',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Jorge Luis Ortiz Caceres',
        Tribu: '',
    },
    {
        Name: 'Paul_Lee',
        City: 'Buenos Aires',
        Country: 'Argentina',
        Email: 'leepaul1008@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '19/11/2021',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Paul Antonio Lee',
        Tribu: '',
    },
    {
        Name: 'Francisco_Jimenez',
        City: 'CDMX',
        Country: 'México',
        Email: 'pamsho09@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '30/09/2022',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Francisco Daniel Jiménez Fernández',
        Tribu: '',
    },
    {
        Name: 'Nicolás_Rivera',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'ericknicolas.rc93@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '07/06/2022',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Erick Nicolás Rivera Cabrera',
        Tribu: '',
    },
    {
        Name: 'Dinorath_Espinoza',
        City: 'Buenos Aires',
        Country: 'Argentina',
        Email: '',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '19/03/2021',
        'Info extra': '',
        'Job Title': 'UX/UI Designer',
        'Mes de cumple': '',
        'Nombre completo': 'Dinorath Raquel Espinoza Galicia',
        Tribu: '',
    },
    {
        Name: 'Camila_Cuervo',
        City: 'Buenos Aires',
        Country: 'Argentina',
        Email: 'camilacuervo@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '18/05/2022',
        'Info extra': '',
        'Job Title': 'UX/UI Designer',
        'Mes de cumple': '',
        'Nombre completo': 'Camila Cuervo',
        Tribu: '',
    },
    {
        Name: 'David_Garrido',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'david.ecuador@hotmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '11/02/2022',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'David Sebastián Garrido Garzón',
        Tribu: '',
    },
    {
        Name: 'Erik_Rodriguez',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'erikospanko1@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '14/04/2022',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Erik David Rodriguez Guerrero',
        Tribu: '',
    },
    {
        Name: 'Lucía_Olivera',
        City: 'Buenos Aires',
        Country: 'Argentina',
        Email: 'oliveralucia141@gmail.com',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '29/07/2022',
        'Info extra': '',
        'Job Title': 'UX/UI Designer',
        'Mes de cumple': '',
        'Nombre completo': 'Lucía Olivera',
        Tribu: '',
    },
    {
        Name: 'Flor Bird',
        City: 'Buenos Aires',
        Country: 'Argentina',
        Email: 'florenciabird95@gmail.com / florencia@tinkin.one',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '19/08/2022',
        'Info extra': '',
        'Job Title': 'UX/UI Designer',
        'Mes de cumple': '',
        'Nombre completo': 'Maria Florencia Bird',
        Tribu: '',
    },
    {
        Name: 'Juan_Sulca',
        City: 'Quito',
        Country: 'Ecuador',
        Email: '',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '15/05/2021',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Juan Martin Sulca Coral',
        Tribu: '',
    },
    {
        Name: 'Kevin_Espinosa',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'kevin@tinkin.one',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '31/05/2022',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Kevin Andrés Espinoza Vásquez',
        Tribu: '',
    },
    {
        Name: 'Wagner_Santos',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'wagner@tinkin.one',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '15/10/2021',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'David Wagner Santos Hernandez',
        Tribu: '',
    },
    {
        Name: 'Marco_Espinosa',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'marco@tinkin.one',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '18/10/2021',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Marco Andres Espinosa Vasquez',
        Tribu: '',
    },
    {
        Name: 'Jorge_Ortiz',
        City: 'Quito',
        Country: 'Ecuador',
        Email: '',
        'Favorite Dessert': '',
        'Fecha de nacimiento': '',
        'Fecha salida': '01/09/2019',
        'Info extra': '',
        'Job Title': 'Developer',
        'Mes de cumple': '',
        'Nombre completo': 'Jorge Ortiz',
        Tribu: '',
    },
    {
        Name: 'Dany_Orellana',
        City: 'Quito',
        Country: 'Ecuador',
        Email: 'dorellana@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '25/10/2000',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': 'October',
        'Nombre completo': 'Daniela Orellana',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Andrea',
        City: 'Buenos Aires',
        Country: 'Argentina',
        Email: 'adiaz@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '12/09/1994',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': 'September',
        'Nombre completo': 'Andrea Díaz',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Walter',
        City: 'Lima',
        Country: 'Peru',
        Email: 'whuaynapata@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '18/08/1997',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': 'August',
        'Nombre completo': 'Walter Huaynapata',
        Tribu: 'Desarrollo',
    },
    {
        Name: 'Abdías',
        City: 'Junín',
        Country: 'Peru',
        Email: 'amartinez@tinkin.one',
        'Favorite Dessert': 'Chocolate chip cookies 🍪',
        'Fecha de nacimiento': '03/04/2000',
        'Fecha salida': '',
        'Info extra': '',
        'Job Title': 'Pasante',
        'Mes de cumple': 'April',
        'Nombre completo': 'Abdías Martinez',
        Tribu: 'Desarrollo',
    },
];

export const lambdaHandler = async (): Promise<void> => {
    const devs = developers
        .filter((dev) => dev.Tribu === 'Desarrollo')
        .map((dev) => ({
            name: dev.Name,
            fullName: dev['Nombre completo'],
            email: dev.Email,
        }))
        .map((dev) => ({
            PutRequest: {
                Item: {
                    id: { S: randomUUID() },
                    createdAt: { N: Date.now().toString() },
                    updatedAt: { N: Date.now().toString() },
                    pairHistory: { L: [] },
                    ...Object.entries(dev).reduce((acc, [key, value]) => ({ ...acc, [key]: { S: value } }), {}),
                },
            },
        }));

    const params: BatchWriteItemCommandInput = {
        RequestItems: {
            [`developers-${process.env.ENVIRONMENT}`]: devs,
        },
    };

    try {
        const data = await ddbDocClient.send(new BatchWriteItemCommand(params));
        logger.info('[Lambda invoked] Creating devs', {
            details: data,
        });
    } catch (err) {
        logger.error('[Lambda invoked] Error crating devs on DB', {
            details: { err },
        });
    }
};
